""" Using the starting and ending values of your car’s odometer, 
            and the measure of fuel consumed, 
            calculate the number of stops one should make for refuelling 
            while travelling from Bangalore to Goa, 
            a distance of 560 kms.
"""
starting_value=input("enter the number")

ending_value =input("enter the number")
flue_filled=input("enter the number")
distance=560
print(distance)

milage=(distance/flue_filled)
print(milage)  

